name: New branch created

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  create-pr:
    if: ${{ !contains(github.event.head_commit.message, '--skip-pr') }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Create PR
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Check if PR already exists
        id: check_pr
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          PR_EXISTS=$(gh pr list --head "$BRANCH_NAME" --json number --jq '. | length')
          echo "pr_exists=$PR_EXISTS" >> $GITHUB_ENV


      - name: Stop if PR already exists
        if: env.pr_exists != '0'
        run: |
          echo "A PR from this branch already exists. Skipping creation."

      - name: Last commit message
        run: |
          echo Last commit: ${{ github.event.head_commit.message }}


      - name: Get the base branch
        id: base_branch
        if: env.pr_exists == '0'
        run: |
          echo "base_branch=development" >> $GITHUB_ENV

    - name: Create Pull Request
        id: create_pr
        if: env.pr_exists == '0'
        uses: peter-evans/create-pull-request@v5
        with:
          base: ${{ env.base_branch }}
          branch: ${{ github.ref_name }}  # Use 'branch' instead of 'head'
          title: "Auto PR from ${{ github.ref_name }}"
          body: "This PR was automatically created for branch ${{ github.ref_name }}."
          draft: false
          labels: patch



      # - name: Set up Node
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*
      #     cache: 'yarn'

      # - name: Install dependencies
      #   run: yarn install

      # - name: Check types
      #   run: yarn test --ci

      # - name: Build package
      #   run: yarn build --silent 2>/dev/null # TODO: resolve "Module level directives cause errors when bundled, 'use client' was ignored."
