name: Tests

on:
  pull_request:
    types:
      - edited
      - opened
      - synchronize
    branches:
      - 'main'
      - 'development'
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'
    tags:
      - '*'

jobs:
  run-ci:
    if: ${{ !contains(github.event.head_commit.message, '--skip-ci') }}

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    name: Run Type Check & Linters
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Check types
        run: yarn test --ci

      - name: Build package
        run: yarn build --silent 2>/dev/null # TODO: resolve "Module level directives cause errors when bundled, 'use client' was ignored."
